# Generated by Django 2.2.5 on 2019-09-28 03:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, null=True, verbose_name='詳細情報')),
                ('is_published', models.BooleanField(default=False, verbose_name='タイムテーブルの公開')),
            ],
        ),
    ]
