# Generated by Django 2.2.5 on 2019-09-28 04:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
