# Generated by Django 2.2.5 on 2019-09-28 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0002_timetable_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTableColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='列名')),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='タイムテーブルID', to='timetables.TimeTable')),
            ],
        ),
    ]
