# Generated by Django 2.2.5 on 2019-09-28 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0003_timetablecolumn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetablecolumn',
            name='table_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='timetables.TimeTable', verbose_name='タイムテーブルID'),
        ),
    ]
