# Generated by Django 2.2.5 on 2019-09-28 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0004_auto_20190928_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTableRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.TimeField(verbose_name='開始時刻')),
                ('duration', models.DurationField(verbose_name='持続時間')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='timetables.TimeTable', verbose_name='タイムテーブル')),
            ],
        ),
    ]
