# Generated by Django 2.2.5 on 2019-09-28 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0005_timetablerow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetablecolumn',
            old_name='table_id',
            new_name='table',
        ),
    ]
