# Generated by Django 2.2.5 on 2019-09-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0006_auto_20190928_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_name', models.CharField(max_length=100, verbose_name='発表者氏名')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('status', models.CharField(choices=[('AC', 'Accepted'), ('WL', 'Waitlist'), ('RJ', 'Rejected'), ('DC', 'Declined'), ('UK', 'Unknown')], default='UK', max_length=2, verbose_name='ステータス')),
                ('tag', models.CharField(max_length=100, verbose_name='タグ')),
                ('talk_language', models.CharField(choices=[('日(JA)', '日本語(Japanese)'), ('英(EN)', '英語(English)')], max_length=5, verbose_name='発表言語')),
                ('slide_language', models.CharField(choices=[('日(JA)', '日本語(Japanese)'), ('英(EN)', '英語(English)'), ('日英(Both)', '日英両方(JA & EN)')], max_length=8, verbose_name='スライドの言語')),
                ('target_audiences', models.CharField(choices=[('BG', 'Beginner'), ('IM', 'Intermidiate'), ('AV', 'Advanced'), ('AL', 'All')], max_length=2, verbose_name='想定する対象者層')),
            ],
        ),
    ]
